# safelist
branches:
  only:
  - master

os:
  - linux

sudo: true

language: c

compiler:
  - gcc-5

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5

before_script:
  - wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz -O /tmp/autoconf-2.69.tar.gz
  - pushd /tmp && tar -xvzf autoconf-2.69.tar.gz && cd autoconf-2.69 && ./configure --prefix=/tmp/mine && make && make install && popd
  - wget http://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz -O /tmp/automake-1.15.tar.gz
  - pushd /tmp && tar -xvzf automake-1.15.tar.gz && cd automake-1.15 && ./configure --prefix=/tmp/mine && make && make install && popd
  - wget http://ftp.gnu.org/gnu/texinfo/texinfo-6.3.tar.gz -O /tmp/texinfo-6.3.tar.gz
  - pushd /tmp && tar -xvzf texinfo-6.3.tar.gz && cd texinfo-6.3 && ./configure --prefix=/tmp/mine && make && make install && popd
  - wget https://bitbucket.org/marcomaggi/re2/downloads/re2-0.3.2.tar.xz -O /tmp/re2-0.3.2.tar.gz
  - pushd /tmp && tar -xvzf re2-0.3.2.tar.gz && cd re2-0.3.2 && ./configure --prefix=/tmp/mine && make && make install && popd

script:
  - export PATH=/tmp/mine/bin:$PATH
  - sh ./autogen.sh
  - ./configure --enable-maintainer-mode
  - make -j4 all && make -j4 check

notifications:
email: true

