# .travis.yml --
#
# Travis CI configuration for CRE2.

# About compiler  packages.  We  select build by  build the  packages to
# install; it should speed up preparation.  By putting a single "addons"
# key the  top level: we would  cause all the compilers  to be installed
# for all the builds in the matrix; we do not want this.

# About compiler  selection.  We  select the compiler  we want  with the
# "compiler" key.  This  should set the environment variable  CXX to the
# associated compiler  executable; I am  not sure that it  actually does
# it.  Example:  selecting "g++-7" as compiler  causes CXX to be  set to
# "g++",  but is  it the  correct executable?   I think  not!  For  this
# reason I explicitly select the compiler  by setting CXX on the command
# line of "configure".  (Marco Maggi; Wed May 24, 2017)

# About  dependency  packages.   We install  dependency  packages  under
# "/tmp/mine".  So we need the following in every script:
#
#   export PATH=/tmp/mine/bin:$PATH;
#   export LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
#   export PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;
#
# otherwise the installed packages will not be found and used correctly.


sudo: false
language: c

# Let's just look at the project's dashboard at Travis CI's site.
#
notifications:
  email: false

# We do no git operations, so set this to the minimum.
#
git:
  depth: 1

branches:
  only:
    - master

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  fast_finish: true

  include:
    # Plain build under Ubuntu GNU+Linux "trusty", GCC 5.
    - os: linux
      dist: trusty
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-5
            - g++-5
      install:
        - ./meta/travis-ci/install-re2.sh
      script: |
        echo CC=$CC; $CC --version;
        echo CXX=$CXX; $CXX --version;
        export PATH=/tmp/mine/bin:$PATH;
        export LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
        export PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;
        sh ./autogen.sh;
        ./configure --enable-maintainer-mode CC=/usr/bin/gcc-5 CXX=/usr/bin/g++-5;
        make all;
        make check;

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 6.
    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-6
            - g++-6
      install:
        - ./meta/travis-ci/install-re2.sh
      script: |
        echo CC=$CC; $CC --version;
        echo CXX=$CXX; $CXX --version;
        export PATH=/tmp/mine/bin:$PATH;
        export LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
        export PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;
        sh ./autogen.sh;
        ./configure --enable-maintainer-mode CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6;
        make all;
        make check;

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 7.
    - os: linux
      dist: trusty
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-7
            - g++-7
      install:
        - ./meta/travis-ci/install-re2.sh
      script: |
        echo CC=$CC; $CC --version;
        echo CXX=$CXX; $CXX --version;
        export PATH=/tmp/mine/bin:$PATH;
        export LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
        export PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;
        sh ./autogen.sh;
        ./configure --enable-maintainer-mode CC=/usr/bin/gcc-7 CXX=/usr/bin/g++-7;
        make all;
        make check;

    # Plain build  under Ubuntu GNU+Linux "trusty",  CLang automatically
    # selected by Travis CI.
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      compiler: clang
      install:
        - ./meta/travis-ci/install-re2.sh
      script: |
        echo CC=$CC; $CC --version;
        echo CXX=$CXX; $CXX --version;
        export PATH=/tmp/mine/bin:$PATH;
        export LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
        export PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;
        sh ./autogen.sh;
        ./configure --enable-maintainer-mode;
        make all;
        make check;

    # Plain build under OS X, XCode 7.3, CLang automatically selected by
    # Travis CI.
    - os: osx
      osx_image: xcode7.3
      compiler: clang++
      install:
        - ./meta/travis-ci/install-re2.sh
      script: |
        echo CC=$CC; $CC --version;
        echo CXX=$CXX; $CXX --version;
        export PATH=/tmp/mine/bin:$PATH;
        export LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
        export PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;
        LIBTOOLIZE=glibtoolize sh ./autogen.sh;
        ./configure --enable-maintainer-mode;
        make all;
        make check;

    # Plain build under OS X, XCode 8.3, CLang automatically selected by
    # Travis CI.
    - os: osx
      osx_image: xcode8.3
      compiler: clang++
      install:
        - ./meta/travis-ci/install-re2.sh
      script: |
        echo CC=$CC; $CC --version;
        echo CXX=$CXX; $CXX --version;
        export PATH=/tmp/mine/bin:$PATH;
        export LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
        export PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;
        LIBTOOLIZE=glibtoolize sh ./autogen.sh;
        ./configure --enable-maintainer-mode;
        make all;
        make check;

    # Codecov support under Ubuntu GNU+Linux "trusty", GCC 7.
    - os: linux
      dist: trusty
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - texinfo
            - gcc-7
            - g++-7
      install:
        - ./meta/travis-ci/install-re2.sh
      script: |
        echo CC=$CC; $CC --version;
        echo CXX=$CXX; $CXX --version;
        export PATH=/tmp/mine/bin:$PATH;
        export LD_LIBRARY_PATH=/tmp/mine/lib:$LD_LIBRARY_PATH;
        export PKG_CONFIG_PATH=/tmp/mine/lib/pkgconfig:$PKG_CONFIG_PATH;
        sh ./autogen.sh;
        ./configure --enable-maintainer-mode CC=/usr/bin/gcc-7 CXX=/usr/bin/g++-7 CFLAGS='-O0 --coverage' CXXFLAGS='-O0 --coverage';
        make all;
        make check;
      after_success:
        bash <(curl -s https://codecov.io/bash) -xgcov-7

### end of file
